#!/usr/bin/env bash
# Run with sudo. Restores real visitor IPs in Nginx and only lets Cloudflare reach ports 80/443.
# Re-run occasionally: Cloudflare's IP ranges change rarely but do change.
set -euo pipefail

v4=$(curl -fsSL https://www.cloudflare.com/ips-v4)
v6=$(curl -fsSL https://www.cloudflare.com/ips-v6)

conf=/etc/nginx/conf.d/cloudflare-realip.conf
{
  echo "# Generated by cloudflare-setup.sh on $(date -I)"
  for ip in $v4 $v6; do echo "set_real_ip_from $ip;"; done
  echo "real_ip_header CF-Connecting-IP;"
} > "$conf"
nginx -t && systemctl reload nginx
echo "Wrote $conf"

ufw allow OpenSSH
for ip in $v4 $v6; do
  ufw allow proto tcp from "$ip" to any port 80,443 comment cloudflare >/dev/null
done
ufw --force enable
ufw status | head -20
